### ISSUE TITLE
ents error while trying to run baseline model. Anyone else faced this issue ?

### ISSUE THREAD

**Issue by harinishritp1** [Legal-NLP-EkStep/legal_NER#2]
\legal_NER\data_preparation.py", line 265, in get_sentence_docs
    print(len(combined_docs.ents))
AttributeError: 'NoneType' object has no attribute 'ents'

Can someone help with this error?

**Comment by prathameshk** [comment]
What input are you passing? It seems that combined_doc is None which can happen due to improper input.

**Comment by harinishritp1** [comment]
I'm running the script mentioned in readme.I pasted the script in a .py file and ran it. Is that correct ?

**Comment by prathameshk** [comment]
There could be an issue with downloading the text from IndianKanoon site. I have replaced the file. Please try with that

**Comment by amant555** [comment]
@harinishritp1 I will be closing this issue. If its still present, feel free to re-open.

**Comment by AnshSinghal** [comment]
Seperating Preamble took 0.03706192970275879
Creating doc for judgement  took 68.93066644668579
1342
Creating doc for preamble  took 0.9695842266082764
Combining took 0.054250240325927734
⚠ There was some issue while performing postprocessing, skipping
postprocessing...
Traceback (most recent call last):
  File "/kaggle/working/legal_NER/run_inference.py", line 93, in <module>
    precedent_counts = get_unique_precedent_count(combined_doc)
  File "/kaggle/working/legal_NER/postprocessing_utils.py", line 869, in get_unique_precedent_count
    clusters=doc.user_data['precedent_clusters']
KeyError: 'precedent_clusters'


I am getting this error.
