### ISSUE TITLE
problem with .spacy data format

### ISSUE THREAD

**Issue by antoniakrm** [Legal-NLP-EkStep/legal_NER#3]
I am trying to evaluate the baseline model on the dev set you provide by using the "spacy evaluate" command from https://spacy.io/api/cli#evaluate

I am getting this error and bad NER per type score: 
Token indices sequence length is longer than the specified maximum sequence length for this model (815 > 512). Running this sequence through the model will result in indexing errors

Could you maybe check if the dev.spacy dataset is tokenized correctly?

<img width="711" alt="image" src="https://user-images.githubusercontent.com/51932024/205285037-09e8146a-5ba5-43fb-87ad-657bc81fa840.png">

**Comment by amant555** [comment]
Hi @antoniakrm,
I have check the data and there are no issue with  the data provided at [link](https://github.com/Legal-NLP-EkStep/legal_NER/tree/main/training/Combined_Data_Judgement_Preamble_spacy_format). I have personally checked and re-ran the results.
I am adding them here for your reference. 
<img width="893" alt="Screenshot 2022-12-06 at 11 54 16" src="https://user-images.githubusercontent.com/49357028/205837520-7dc496a3-f835-44f2-aacc-982991f8e657.png">

Please refer to above results. 
I will close this issue for now. In case you have any questions feel free to re-open this issue.
