### ISSUE TITLE
NER data to spacy conversion script

### ISSUE THREAD

**Issue by Dhanachandra** [Legal-NLP-EkStep/legal_NER#4]
Could you please share your script to convert LNER dataset to spacy format.

**Comment by prathameshk** [comment]
We used prodigy tool used for annotations. So we got the data in spacy format which is present here https://github.com/Legal-NLP-EkStep/legal_NER/tree/main/training/Combined_Data_Judgement_Preamble_spacy_format. We then converted this spacy format to json format which is present https://storage.googleapis.com/indianlegalbert/OPEN_SOURCED_FILES/NER/NER_TRAIN.zip & https://storage.googleapis.com/indianlegalbert/OPEN_SOURCED_FILES/NER/NER_DEV.zip

You can create your own script to convert from json to spacy format.
