### ISSUE TITLE
raise ValueError('{!r} is not a valid parameter name'.format(name))

### ISSUE THREAD

**Issue by magick93** [Legal-NLP-EkStep/legal_NER#7]
Hello

I'm trying to run the following:

```
!pip install https://huggingface.co/opennyaiorg/en_legal_ner_trf/resolve/main/en_legal_ner_trf-any-py3-none-any.whl


# Using spacy.load().
import spacy
nlp = spacy.load("en_legal_ner_trf")
text = "Section 319 Cr.P.C. contemplates a situation where the evidence adduced by the prosecution for Respondent No.3-G. Sambiah on 20th June 1984"
doc = nlp(text)

# Print indentified entites
for ent in doc.ents:
     print(ent,ent.label_)

##OUTPUT     
#Section 319 PROVISION
#Cr.P.C. STATUTE
#G. Sambiah RESPONDENT
#20th June 1984 DATE

```
I get this error  - `raise ValueError('{!r} is not a valid parameter name'.format(name))`

I'm using python 3.11.2.

Do you have any suggestions?

Thanks

-----

Using python 3.9.0 I get this error:

```
TypeError: issubclass() arg 1 must be a class
```

**Comment by prathameshk** [comment]
If you are looking to run the pretrained model then it is encouraged that you use opennyai library https://github.com/OpenNyAI/Opennyai

**Comment by tianyu-z** [comment]
pip uninstall pydantic && pip install pydantic
I believe this is a problem from spacy.
This works for me. Credit to: https://stackoverflow.com/questions/75978880/spacy-python-package-no-longer-runs
