### ISSUE TITLE
Regarding Evaluation

### ISSUE THREAD

**Issue by BadrinathMJ** [Legal-NLP-EkStep/legal_NER#8]
Can we use the Hit_rate, Recall and precision for evaluating the results of named entity recognition?
Hit_rate: If model has extracted correct named entity from text will be considered as one hit with respect to original document.

**Comment by prathameshk** [comment]
The test data is now available https://huggingface.co/datasets/opennyaiorg/InLegalNER.
You can use custom evaluation metric on this data.
